name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Change to 'windows-latest' if you want to run on a Windows runner.

    strategy:
      matrix:
        java: [17, 11]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Ensure gradlew is executable
      run: chmod +x gradlew

    - name: Build with Gradle
      run: |
        cd $GITHUB_WORKSPACE  # Ensure we are in the root of the repository
        if [[ "$RUNNER_OS" == "Windows" ]]; then ./gradlew.bat build --no-daemon; else ./gradlew build --no-daemon; fi

    - name: Run tests
      run: |
        cd $GITHUB_WORKSPACE  # Ensure we are in the root of the repository
        if [[ "$RUNNER_OS" == "Windows" ]]; then ./gradlew.bat test --no-daemon; else ./gradlew test --no-daemon; fi
