name: Java CI with javac

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: List files in src directory
        run: |
          cd src/main/roguegame
          ls -l

      - name: Compile Java files
        run: javac -d out src/main/roguegame/**/*.java

      - name: Run Java Application
        run: java -cp out roguegame.DungeonGame
