name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Verify project structure
        run: ls -R

      - name: Grant execute permission for Gradle
        run: chmod +x ./ROGUE/gradlew

      - name: Build with Gradle
        run: cd ROGUE && ./gradlew build

