name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Debug: List all files in the project directory
      - name: Debug - List all project files
        run: ls -lahR

      # Debug: Check if gradlew exists inside ROGUE/
      - name: Debug - List files inside ROGUE directory
        run: ls -lah ROGUE/

      # Ensure gradlew is present, exit if missing
      - name: Verify Gradle wrapper exists
        run: |
          if [ ! -f ROGUE/gradlew ]; then
            echo "❌ Error: gradlew not found!"
            exit 1
          fi

      # Ensure gradlew has execute permissions
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ROGUE/gradlew

      # Build project using Gradle
      - name: Build with Gradle
        run: cd ROGUE && ./gradlew build
